# Generated by Django 5.1.4 on 2025-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_behavioraldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioraldata',
            name='biometric_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
