# Generated by Django 5.1.4 on 2025-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_behavioraldata_biometric_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='behaviour_security',
            field=models.BooleanField(default=False),
        ),
    ]
